ACTION_MARKER = ("Action", "action_marker")

PAC_GUID = "7db159f2-1eb2-425f-aaac-5492e36d755b"
PAC_POSITIONS = (-1500, -210)

DICE_POSITIONS = [(-950, -50), (-950, 50)]
DICE_GUID = "fdbd1ec7-702f-4c29-bd6f-3f628af80a39"
DICE_FACES = {
    1: "Face1",
    2: "Face2",
    3: "Face3",
    4: "Face4",
    5: "Face5",
    6: "",
}

NO_ACTIONS = ["PAC", "Dice", "Map", "Terrain"]

KEYWORDS = [
    "4 Points Gaming Club",
    "A.I.M.",
    "A.R.G.U.S.",
    "Acolytes",
    "Agency X",
    "Agents Of Atlas",
    "Alpha Flight",
    "Amazon",
    "Animal",
    "Annihilators",
    "Apokolips",
    "Arakko",
    "Arkham Asylum",
    "Armor",
    "Asgardian",
    "Assassin",
    "Atlantis",
    "Avengers",
    "Batman Family",
    "Battleworld: Other",
    "Birds Of Prey",
    "Black Lantern Corps",
    "Black Order",
    "Blue Lantern Corps",
    "Brood",
    "Brotherhood Of Mutants",
    "Brute",
    "Cabal",
    "Camelot",
    "Celebrity",
    "Central City",
    "Champions",
    "Chaotic",
    "Coast City",
    "Cosmic",
    "Court Of Owls",
    "Crime Syndicate",
    "Damage Control",
    "Dark Avengers",
    "Dark Knights",
    "Darkseid'S Elite",
    "Deadpool Corps",
    "Defenders",
    "Deity",
    "Demon Legion",
    "Detective",
    "Doom Patrol",
    "Dragon",
    "Elders Of The Universe",
    "Endless",
    "Entity",
    "Eternal",
    "Evil",
    "Excalibur",
    "Exiles",
    "Fantastic Four",
    "Female Furies",
    "Femizons",
    "Frightful Four",
    "Future",
    "Gemworld",
    "Generation X",
    "Ghost Realm",
    "Gnome",
    "God Squad",
    "Gorilla City",
    "Gotham City",
    "Gotham City Sirens",
    "Gotham City Underworld",
    "Green Lantern Corps",
    "Guardians Of The Galaxy",
    "H.A.M.M.E.R.",
    "H.A.T.E.",
    "Hawkins",
    "Hellfire Club",
    "Hellions",
    "Herald",
    "Heroes For Hire",
    "Hive",
    "Horsemen",
    "Howling Commandos",
    "Hulkbusters",
    "Hydra",
    "Illuminati",
    "Indigo Tribe",
    "Infinity Watch",
    "Initiative",
    "Injustice League",
    "Injustice Society",
    "Intelligencia",
    "Invaders",
    "Justice League",
    "Justice League Dark",
    "Justice Society",
    "Kree",
    "Kryptonian",
    "Lady Liberators",
    "Latveria",
    "League Of Assassins",
    "Legion Of Doom",
    "Legion Of Monsters",
    "Legion Of Super Heroes",
    "Legion Of Super Pets",
    "Legion Of Super Villains",
    "Lethal Legion",
    "Leviathan",
    "Lost Lanterns",
    "M.O.D.O.K.'S 11",
    "Maggia",
    "Marauders",
    "Marksman",
    "Martial Artist",
    "Marvel Knights",
    "Masters Of Evil",
    "Maximum Carnage",
    "Metropolis",
    "Midnight Sons",
    "Minions Of Thanos",
    "Mojoverse",
    "Monster",
    "Monstrosity",
    "Morlocks",
    "Mystical",
    "Neutral",
    "New Gods",
    "New Guardians",
    "New Mutants",
    "New Warriors",
    "Nextwave",
    "Nova Corps",
    "Offenders",
    "Orange Lantern Corps",
    "Outlaws",
    "Outsiders",
    "Past",
    "Pet Avengers",
    "Phoenix Force",
    "Pilot",
    "Pirate",
    "Podcaster",
    "Police",
    "Politician",
    "Project Cadmus",
    "Quiet Council",
    "Ravagers",
    "Red Lantern Corps",
    "Reporter",
    "Revengers",
    "Robot",
    "Rogues",
    "Royal Flush Gang",
    "Ruler",
    "Runaways",
    "S.H.I.E.L.D.",
    "S.W.O.R.D.",
    "Santa'S Workshop",
    "Savage Land",
    "Scientist",
    "Secret Six",
    "Secret Society Of Super Villains",
    "Secret Warriors",
    "Sentinel",
    "Sentinels Of Magic",
    "Seven Soldiers",
    "Shadowpact",
    "Shi'Ar",
    "Sinestro Corps",
    "Sinister Syndicate",
    "Six Pack",
    "Skeleton Crew",
    "Skrulls",
    "Soldier",
    "Spaceknight",
    "Speedster",
    "Spider Man Family",
    "Spy",
    "Squadron Supreme",
    "Star City",
    "Star Sapphires",
    "Starjammers",
    "Stark Industries",
    "Suicide Squad",
    "Superman Revenge Squad",
    "Symbiote",
    "Tarot",
    "Teen Titans",
    "The Hand",
    "Thunderbolts",
    "Thundercats",
    "Time Masters",
    "Time Stealers",
    "Trinity",
    "Ultimates",
    "Ultraviolet Corps",
    "Upside Down",
    "Utopia",
    "Vampire Brood",
    "Vehicle",
    "Wakanda",
    "Warbound",
    "Warp World",
    "Warrior",
    "Weapon X",
    "White Lantern Corps",
    "Wild Pack",
    "Wrecking Crew",
    "X Factor",
    "X Force",
    "X Men",
    "Young Avengers",
    "Young Justice",
    "Zombie Horde",
]

TEAM_ABILITIES = [
    "Avengers",
    "Avengers Initiative",
    "Batman Ally",
    "Batman Enemy",
    "Brotherhood Of Mutants",
    "Calculator",
    "Cosmic Energy",
    "Crime Syndicate",
    "Defenders",
    "Fantastic Four",
    "Green Lantern Corps",
    "Guardians",
    "Hydra",
    "Hypertime",
    "Injustice League",
    "Justice League",
    "Justice Society",
    "Kingdom Come",
    "Legion Of Super Heroes",
    "Masters Of Evil",
    "Minions Of Doom",
    "Mystics",
    "Outsiders",
    "Police",
    "Shield",
    "Sinister Syndicate",
    "Skrulls",
    "Snowfall",
    "Spider Man",
    "Suicide Squad",
    "Superman Ally",
    "Superman Enemy",
    "Team Player",
    "Titans",
    "Ultimates",
    "Underworld",
    "Wakanda",
    "Wonder Woman Ally",
    "X Men",
]

FILTER_CHOICE_LIST = [KEYWORDS, TEAM_ABILITIES]