ACTION_MARKER = ("Action", "action_marker")

PAC_GUID = "7db159f2-1eb2-425f-aaac-5492e36d755b"
PAC_POSITIONS = (-1500, -210)

BUTTON_COLORS = ["#007fc2", "#4da5d4", "#99cce7", "#f14a50", "#f68e92", "#fbd2d3", "#82a43a", "#a8bf75", "#cddbb0", ]

DICE_POSITIONS = [(-950, -50), (-950, 50)]
DICE_GUID = "fdbd1ec7-702f-4c29-bd6f-3f628af80a39"
DICE_FACES = {
    1: "Face1",
    2: "Face2",
    3: "Face3",
    4: "Face4",
    5: "Face5",
    6: "",
}

GRID_SIZE = 100
NOT_SQUARE_SIZES = ["1x2", "2x4", "3x6"]

NO_ACTIONS = ["PAC", "Dice", "Map", "Terrain"]

KEYWORDS = [
    "4 Points Gaming Club",
    "A.I.M.",
    "A.R.G.U.S.",
    "Abomaste",
    "Acolytes",
    "Age Of Apocalypse",
    "Agency X",
    "Agents Of Atlas",
    "All New X Men",
    "All Star Squadron",
    "Alpha Flight",
    "Amazon",
    "Animal",
    "Annihilators",
    "Apokolips",
    "Arakko",
    "Arkham Asylum",
    "Armor",
    "Asgardian",
    "Assassin",
    "Atlantis",
    "Authority",
    "Avengers",
    "Bajoran",
    "Batman Family",
    "Batroc'S Brigade",
    "Battleworld: Asgard",
    "Battleworld: Other",
    "Battleworld: Regency",
    "Battleworld: Spider Island",
    "Battleworld: The Valley",
    "Battleworld: Weirdworld",
    "Birds Of Prey",
    "Black Lantern Corps",
    "Black Order",
    "Blue Lantern Corps",
    "Bombshells",
    "Borg",
    "Brood",
    "Brotherhood Of Evil",
    "Brotherhood Of Mutants",
    "Brute",
    "Cabal",
    "Camelot",
    "Cardassian",
    "Celebrity",
    "Central City",
    "Champions",
    "Chaotic",
    "Circle Of Four",
    "Circus Of Crime",
    "Coast City",
    "Codex",
    "Corporate Ministry",
    "Corporation",
    "Cosmic",
    "Council Of Kangs",
    "Court Of Owls",
    "Crime Syndicate",
    "Crystalium",
    "D Generation X",
    "Damage Control",
    "Dark Avengers",
    "Dark Knights",
    "Dark X Men",
    "Darkseid'S Elite",
    "Deadpool Corps",
    "Defenders",
    "Defiance",
    "Deity",
    "Demon Boss",
    "Demon Legion",
    "Detective",
    "Deviant",
    "Dominion",
    "Doom Patrol",
    "Dragon",
    "Earth X",
    "Elders Of The Universe",
    "Emissaries Of Evil",
    "Endless",
    "Enforcers",
    "Entity",
    "Eternal",
    "Evil",
    "Evolution",
    "Excalibur",
    "Exiles",
    "Extreme Justice",
    "Fallen Angels",
    "Fantastic Four",
    "Fawcett City",
    "Federation",
    "Female Furies",
    "Femizons",
    "Ferengi",
    "Flashpoint",
    "Foot Clan",
    "Forgotten Heroes",
    "Four Horsewomen",
    "Fraternity Of Raptors",
    "Freedom Fighters",
    "Freedom Force",
    "Frightful Four",
    "Future",
    "Gemworld",
    "Generation X",
    "Ghost Realm",
    "Gnome",
    "God Squad",
    "Godwatch",
    "Gorilla City",
    "Gotham City",
    "Gotham City Sirens",
    "Gotham City Underworld",
    "Great Lakes Avengers",
    "Green Lantern Corps",
    "Guardians Of The Galaxy",
    "H.A.M.M.E.R.",
    "H.A.T.E.",
    "Hammer Industries",
    "Hawkins",
    "Heenan Family",
    "Hellfire Club",
    "Hellions",
    "Herald",
    "Heroes For Hire",
    "Hive",
    "Holodeck",
    "Horsemen",
    "Horsemen Of Apocalypse",
    "Howling Commandos",
    "Hulkbusters",
    "Hulked Out Heroes",
    "Hydra",
    "Illuminati",
    "Imperial Guard",
    "Indigo Tribe",
    "Infinity Watch",
    "Inhumans",
    "Initiative",
    "Injustice Gang",
    "Injustice League",
    "Injustice Society",
    "Intelligencia",
    "Invaders",
    "Jean Grey School For Higher Learning",
    "Jem'Hadar",
    "Justice League",
    "Justice League Dark",
    "Justice League International",
    "Justice League Of China",
    "Justice Lords",
    "Justice Society",
    "K'Un Lun",
    "Keystone City",
    "Klingon",
    "Kree",
    "Kryptonian",
    "Lady Liberators",
    "Latveria",
    "League Of Assassins",
    "Legion Of Doom",
    "Legion Of Monsters",
    "Legion Of Super Heroes",
    "Legion Of Super Pets",
    "Legion Of Super Villains",
    "Lethal Legion",
    "Leviathan",
    "Loners",
    "Lost Lanterns",
    "M.O.D.O.K.'S 11",
    "Maggia",
    "Mandarin'S Minions",
    "Marauders",
    "Marksman",
    "Martial Artist",
    "Marvel Diva",
    "Marvel Knights",
    "Masters Of Evil",
    "Maximum Carnage",
    "Metal Men",
    "Metropolis",
    "Midnight Sons",
    "Minions Of Thanos",
    "Mirror Universe",
    "Mojoverse",
    "Monster",
    "Monstrosity",
    "Morlocks",
    "Mutanimals",
    "Mutant Liberation Front",
    "Mystery Inc.",
    "Mystical",
    "Negative Zone",
    "Neutral",
    "New Gods",
    "New Guardians",
    "New Mutants",
    "New Warriors",
    "New World Order",
    "Nextwave",
    "Nova Corps",
    "Offenders",
    "Omega Flight",
    "Omega Men",
    "Orange Lantern Corps",
    "Outlaws",
    "Outsiders",
    "Past",
    "Pet Avengers",
    "Phantom Zone",
    "Phenomenal Flair",
    "Phoenix Force",
    "Pilot",
    "Pirate",
    "Planetary",
    "Planetary Union",
    "Podcaster",
    "Police",
    "Politician",
    "Power Elite",
    "Power Pack",
    "Power Rangers",
    "Pro Registration",
    "Project Cadmus",
    "Purple Dragon",
    "Quiet Council",
    "Quintessence",
    "Ravagers",
    "Reavers",
    "Red Lantern Corps",
    "Red Son",
    "Reman",
    "Reporter",
    "Revengers",
    "Robot",
    "Rock & Sock Connection",
    "Rogues",
    "Romulan",
    "Royal Flush Gang",
    "Ruler",
    "Runaways",
    "S.H.I.E.L.D.",
    "S.T.A.R. Labs",
    "S.W.O.R.D.",
    "Santa'S Workshop",
    "Savage Land",
    "Scientist",
    "Secret Six",
    "Secret Society Of Super Villains",
    "Secret Warriors",
    "Sentinel",
    "Sentinels Of Magic",
    "Serpent Society",
    "Seven Soldiers",
    "Shadowpact",
    "Shi'Ar",
    "Sinestro Corps",
    "Sinister Syndicate",
    "Six Pack",
    "Skeleton Army",
    "Skeleton Crew",
    "Skrulls",
    "Society",
    "Soldier",
    "Spaceknight",
    "Spartoi",
    "Species 8472",
    "Speedster",
    "Spider Man Family",
    "Spy",
    "Squadron Sinister",
    "Squadron Supreme",
    "Star City",
    "Star Sapphires",
    "Starfleet",
    "Starforce",
    "Starjammers",
    "Stark Industries",
    "Strike Force Kobra",
    "Suicide Squad",
    "Super Buddies",
    "Super Friends",
    "Superman Revenge Squad",
    "Svartalfheim",
    "Symbiote",
    "Tarot",
    "Task Force",
    "Teen Titans",
    "Terran Empire",
    "Terrifics",
    "The Five",
    "The Hand",
    "Tholian",
    "Thunderbolts",
    "Thundercats",
    "Time Masters",
    "Time Stealers",
    "Tmnt",
    "Tmnt Ally",
    "Tmnt Villain",
    "Triceraton",
    "Trinity",
    "U Foes",
    "Ultimates",
    "Ultraviolet Corps",
    "United Underworld",
    "Upside Down",
    "Utopia",
    "Utrom",
    "V Battalion",
    "Vampire Brood",
    "Vehicle",
    "Vulcan",
    "Wakanda",
    "Warbound",
    "Warp World",
    "Warrior",
    "Warriors Three",
    "Weapon X",
    "Werewolf Pack",
    "White Lantern Corps",
    "Widows",
    "Wild Pack",
    "Winter Guard",
    "Wonders Of The World",
    "Wrecking Crew",
    "Wwe",
    "X Corps",
    "X Factor",
    "X Force",
    "X Men",
    "X Statix",
    "Xindi",
    "Young Avengers",
    "Young Justice",
    "Z Virus",
    "Zodiac",
    "Zombie Horde",
]

TEAM_ABILITIES = [
    "Avengers",
    "Avengers Initiative",
    "Batman Ally",
    "Batman Enemy",
    "Borg",
    "Borg Tactics",
    "Brotherhood Of Mutants",
    "Calculator",
    "Cardassian Union",
    "Cosmic Energy",
    "Crime Syndicate",
    "Defenders",
    "Dominion",
    "Fantastic Four",
    "Federation",
    "Ferengi Alliance",
    "Green Lantern Corps",
    "Guardians",
    "Hydra",
    "Hypertime",
    "Injustice League",
    "Justice League",
    "Justice Society",
    "Kingdom Come",
    "Klingon Empire",
    "Klingon Empire Tactics",
    "Legion Of Super Heroes",
    "Masters Of Evil",
    "Minions Of Doom",
    "Mirror Universe",
    "Mystics",
    "Outsiders",
    "Police",
    "Power Cosmic",
    "Q Continuum",
    "Quintessence",
    "Romulan Star Empire",
    "Romulan Star Empire Tactics",
    "Shield",
    "Sinister Syndicate",
    "Skrulls",
    "Snowfall",
    "Spider Man",
    "Suicide Squad",
    "Superman Ally",
    "Superman Enemy",
    "Team Player",
    "Titans",
    "Ultimates",
    "Underworld",
    "United Federation",
    "Wakanda",
    "Wonder Woman Ally",
    "Wwe",
    "X Men",
]

FILTER_CHOICE_LIST = [KEYWORDS, TEAM_ABILITIES]